version: "3.4"
services:
  my_frontend:
    container_name: my_frontend
    image: node:lts
    working_dir: /home/github/Front
    entrypoint: ["npm", "run", "preview", "--", "--host"]
    volumes:
      - .:/home/github/Front
    tty: true

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
